package com.minger.lexio.ui.theme

import androidx.compose.ui.graphics.Color

// light theme
internal val LightPrimary = Color(0xFF2556E6)
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFDEE1FF)
internal val LightOnPrimaryContainer = Color(0xFF00174A)
internal val LightSecondary = Color(0xFF585E72)
internal val LightOnSecondary = Color(0xFFFFFFFF)
internal val LightSecondaryContainer = Color(0xFFDDE2F9)
internal val LightOnSecondaryContainer = Color(0xFF151B2C)
internal val LightTertiary = Color(0xFF73548F)
internal val LightOnTertiary = Color(0xFFFFFFFF)
internal val LightTertiaryContainer = Color(0xFFF3DAFF)
internal val LightOnTertiaryContainer = Color(0xFF2B0F45)
internal val LightError = Color(0xFFBA1A1A)
internal val LightOnError = Color(0xFFFFFFFF)
internal val LightErrorContainer = Color(0xFFFFDAD6)
internal val LightOnErrorContainer = Color(0xFF410002)
internal val LightBackground = Color(0xFFFFFFFF)
internal val LightOnBackground = Color(0xFF1B1B1F)
internal val LightSurface = Color(0xFFFFFFFF)
internal val LightOnSurface = Color(0xFF1B1B1F)
internal val LightSurfaceVariant = Color(0xFFE4E1E6)
internal val LightOnSurfaceVariant = Color(0xFF46464B)
internal val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
internal val LightSurfaceContainerLow = Color(0xFFFFFFFF)
internal val LightSurfaceContainer = Color(0xFFE4E1E6)
internal val LightSurfaceContainerHigh = Color(0xFFE4E1E6)
internal val LightSurfaceContainerHighest = Color(0xFFC7C5CA)
internal val LightOutline = Color(0xFF77777C)
internal val LightOutlineVariant = Color(0xFFC7C5CA)
internal val LightInverseSurface = Color(0xFF303034)
internal val LightInverseOnSurface = Color(0xFFE4E1E6)
internal val LightInversePrimary = Color(0xFFBAC3FF)
internal val LightSurfaceTint = Color(0xFF2556E6)
internal val LightShadow = Color(0xFF000000)
internal val LightScrim = Color(0xFF000000)

// dark theme
internal val DarkPrimary = Color(0xFFBAC3FF)
internal val DarkOnPrimary = Color(0xFF002B72)
internal val DarkPrimaryContainer = Color(0xFF00409F)
internal val DarkOnPrimaryContainer = Color(0xFFDEE1FF)
internal val DarkSecondary = Color(0xFFC1C6DD)
internal val DarkOnSecondary = Color(0xFF2A3042)
internal val DarkSecondaryContainer = Color(0xFF41465A)
internal val DarkOnSecondaryContainer = Color(0xFFDDE2F9)
internal val DarkTertiary = Color(0xFFE1BCFD)
internal val DarkOnTertiary = Color(0xFF42255D)
internal val DarkTertiaryContainer = Color(0xFF5A3C75)
internal val DarkOnTertiaryContainer = Color(0xFFF3DAFF)
internal val DarkError = Color(0xFFFFB4AB)
internal val DarkOnError = Color(0xFF690005)
internal val DarkErrorContainer = Color(0xFF93000A)
internal val DarkOnErrorContainer = Color(0xFFFFDAD6)
internal val DarkBackground = Color(0xFF1B1B1F)
internal val DarkOnBackground = Color(0xFFE4E1E6)
internal val DarkSurface = Color(0xFF1B1B1F)
internal val DarkOnSurface = Color(0xFFE4E1E6)
internal val DarkSurfaceVariant = Color(0xFF46464B)
internal val DarkOnSurfaceVariant = Color(0xFFC7C5CA)
internal val DarkSurfaceContainerLowest = Color(0xFF1B1B1F)
internal val DarkSurfaceContainerLow = Color(0xFF303034)
internal val DarkSurfaceContainer = Color(0xFF303034)
internal val DarkSurfaceContainerHigh = Color(0xFF46464B)
internal val DarkSurfaceContainerHighest = Color(0xFF46464B)
internal val DarkOutline = Color(0xFF919095)
internal val DarkOutlineVariant = Color(0xFF46464B)
internal val DarkInverseSurface = Color(0xFFE4E1E6)
internal val DarkInverseOnSurface = Color(0xFF303034)
internal val DarkInversePrimary = Color(0xFF2556E6)
internal val DarkSurfaceTint = Color(0xFFBAC3FF)
internal val DarkShadow = Color(0xFF000000)
internal val DarkScrim = Color(0xFF000000)